### ISSUE TITLE
Problems on Windows -- RuntimeError: An attempt has been made to start a new process...

### ISSUE THREAD

**Issue by dougwood** [treszkai/best#5]
I am trying to use BEST for the first time, but am having difficulties.  Here is my test case:
--------------

```
import best

group1_data = [20194, 21159.5, 12460]
group2_data = [13555.5, 0627.5, 11619.5]

best_out = best.analyze_two(group1_data, group2_data)
fig = best.plot_all(best_out)
```

-------------------

I rolled by pymc3 to v3.7 as suggested elsewhere  (see pip list below) and that has improved things, but I am still getting the follow errors:

```
Microsoft Windows [Version 10.0.17763.2565]
(c) 2018 Microsoft Corporation. All rights reserved.

D:\Users\Doug>cd D:\Users\Doug\UltivueSWDev\bayesian_estimator

D:\Users\Doug\UltivueSWDev\bayesian_estimator>python D:\Users\Doug\UltivueSWDev\bayesian_estimator\bayesiand_estimator.py
WARNING (theano.configdefaults): g++ not available, if using conda: `conda install m2w64-toolchain`
WARNING (theano.configdefaults): g++ not detected ! Theano will be unable to execute optimized C-implementations (for both CPU and GPU) and will default to Python implementations. Performance will be severely degraded. To remove this warning, set Theano flags cxx to an empty string.
WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
C:\Program Files\Python37\lib\site-packages\deprecat\classic.py:215: FutureWarning: In v4.0, pm.sample will return an `arviz.InferenceData` object instead of a `MultiTrace` by default. You can pass return_inferencedata=True or return_inferencedata=False to be safe and silence this warning.
  return wrapped_(*args_, **kwargs_)
Auto-assigning NUTS sampler...
Initializing NUTS using jitter+adapt_diag...
C:\Program Files\Python37\lib\site-packages\theano\tensor\elemwise.py:826: RuntimeWarning: divide by zero encountered in log
  variables = ufunc(*ufunc_args, **ufunc_kwargs)
C:\Program Files\Python37\lib\site-packages\theano\tensor\elemwise.py:826: RuntimeWarning: invalid value encountered in multiply
  variables = ufunc(*ufunc_args, **ufunc_kwargs)
C:\Program Files\Python37\lib\site-packages\theano\tensor\elemwise.py:826: RuntimeWarning: invalid value encountered in log
  variables = ufunc(*ufunc_args, **ufunc_kwargs)
Multiprocess sampling (4 chains in 4 jobs)
NUTS: [Group 2 log sigma, Group 1 log sigma, nu - 2.5, Group 2 mean, Group 1 mean]
WARNING (theano.configdefaults): g++ not available, if using conda: `conda install m2w64-toolchain`
WARNING (theano.configdefaults): g++ not detected ! Theano will be unable to execute optimized C-implementations (for both CPU and GPU) and will default to Python implementations. Performance will be severely degraded. To remove this warning, set Theano flags cxx to an empty string.
WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
C:\Program Files\Python37\lib\site-packages\deprecat\classic.py:215: FutureWarning: In v4.0, pm.sample will return an `arviz.InferenceData` object instead of a `MultiTrace` by default. You can pass return_inferencedata=True or return_inferencedata=False to be safe and silence this warning.
  return wrapped_(*args_, **kwargs_)
Auto-assigning NUTS sampler...
Initializing NUTS using jitter+adapt_diag...
C:\Program Files\Python37\lib\site-packages\theano\tensor\elemwise.py:826: RuntimeWarning: divide by zero encountered in log
  variables = ufunc(*ufunc_args, **ufunc_kwargs)
C:\Program Files\Python37\lib\site-packages\theano\tensor\elemwise.py:826: RuntimeWarning: invalid value encountered in multiply
  variables = ufunc(*ufunc_args, **ufunc_kwargs)
C:\Program Files\Python37\lib\site-packages\theano\tensor\elemwise.py:826: RuntimeWarning: invalid value encountered in log
  variables = ufunc(*ufunc_args, **ufunc_kwargs)
Multiprocess sampling (4 chains in 4 jobs)
NUTS: [Group 2 log sigma, Group 1 log sigma, nu - 2.5, Group 2 mean, Group 1 mean]
Traceback (most recent call last):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Users\Doug\UltivueSWDev\bayesian_estimator\bayesiand_estimator.py", line 7, in <module>
  File "C:\Program Files\Python37\lib\multiprocessing\spawn.py", line 105, in spawn_main
    best_out = best.analyze_two(group1_data, group2_data)
  File "C:\Program Files\Python37\lib\site-packages\best\model.py", line 454, in analyze_two
    exitcode = _main(fd)
  File "C:\Program Files\Python37\lib\multiprocessing\spawn.py", line 114, in _main
    trace = model.sample(n_samples, **kwargs)
  File "C:\Program Files\Python37\lib\site-packages\best\model.py", line 78, in sample
    prepare(preparation_data)
  File "C:\Program Files\Python37\lib\multiprocessing\spawn.py", line 225, in prepare
    trace = pm.sample(n_samples, **kwargs)
  File "C:\Program Files\Python37\lib\site-packages\deprecat\classic.py", line 215, in wrapper_function
    _fixup_main_from_path(data['init_main_from_path'])
    return wrapped_(*args_, **kwargs_)
  File "C:\Program Files\Python37\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
  File "C:\Program Files\Python37\lib\site-packages\pymc3\sampling.py", line 575, in sample
    run_name="__mp_main__")
  File "C:\Program Files\Python37\lib\runpy.py", line 263, in run_path
    trace = _mp_sample(**sample_args, **parallel_args)
  File "C:\Program Files\Python37\lib\site-packages\pymc3\sampling.py", line 1491, in _mp_sample
    pkg_name=pkg_name, script_name=fname)
  File "C:\Program Files\Python37\lib\runpy.py", line 96, in _run_module_code
    pickle_backend=pickle_backend,
  File "C:\Program Files\Python37\lib\site-packages\pymc3\parallel_sampling.py", line 443, in __init__
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Program Files\Python37\lib\runpy.py", line 85, in _run_code
    for chain, seed, start in zip(range(chains), seeds, start_points)
  File "C:\Program Files\Python37\lib\site-packages\pymc3\parallel_sampling.py", line 443, in <listcomp>
    exec(code, run_globals)
  File "D:\Users\Doug\UltivueSWDev\bayesian_estimator\bayesiand_estimator.py", line 7, in <module>
    for chain, seed, start in zip(range(chains), seeds, start_points)
  File "C:\Program Files\Python37\lib\site-packages\pymc3\parallel_sampling.py", line 292, in __init__
    best_out = best.analyze_two(group1_data, group2_data)
  File "C:\Program Files\Python37\lib\site-packages\best\model.py", line 454, in analyze_two
    self._process.start()
  File "C:\Program Files\Python37\lib\multiprocessing\process.py", line 112, in start
    trace = model.sample(n_samples, **kwargs)
    self._popen = self._Popen(self)
  File "C:\Program Files\Python37\lib\multiprocessing\context.py", line 322, in _Popen
  File "C:\Program Files\Python37\lib\site-packages\best\model.py", line 78, in sample
    return Popen(process_obj)
    trace = pm.sample(n_samples, **kwargs)
  File "C:\Program Files\Python37\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
  File "C:\Program Files\Python37\lib\site-packages\deprecat\classic.py", line 215, in wrapper_function
    reduction.dump(process_obj, to_child)
    return wrapped_(*args_, **kwargs_)
  File "C:\Program Files\Python37\lib\multiprocessing\reduction.py", line 60, in dump
  File "C:\Program Files\Python37\lib\site-packages\pymc3\sampling.py", line 575, in sample
    ForkingPickler(file, protocol).dump(obj)
    trace = _mp_sample(**sample_args, **parallel_args)
BrokenPipeError: [Errno 32] Broken pipe
  File "C:\Program Files\Python37\lib\site-packages\pymc3\sampling.py", line 1491, in _mp_sample
    pickle_backend=pickle_backend,
  File "C:\Program Files\Python37\lib\site-packages\pymc3\parallel_sampling.py", line 443, in __init__
    for chain, seed, start in zip(range(chains), seeds, start_points)
  File "C:\Program Files\Python37\lib\site-packages\pymc3\parallel_sampling.py", line 443, in <listcomp>
    for chain, seed, start in zip(range(chains), seeds, start_points)
  File "C:\Program Files\Python37\lib\site-packages\pymc3\parallel_sampling.py", line 292, in __init__
    self._process.start()
  File "C:\Program Files\Python37\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Program Files\Python37\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Program Files\Python37\lib\multiprocessing\popen_spawn_win32.py", line 46, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Program Files\Python37\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "C:\Program Files\Python37\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

D:\Users\Doug\UltivueSWDev\bayesian_estimator>pip list
Package            Version
------------------ ---------
affine             2.3.0
aicspylibczi       2.6.0
arviz              0.12.0
atomicwrites       1.4.0
attrs              21.2.0
best               2.0.4
boto3              1.20.24
botocore           1.23.24
cachetools         5.0.0
certifi            2021.10.8
cffi               1.14.5
cftime             1.6.0
click              8.0.3
click-plugins      1.1.1
cligj              0.7.2
colorama           0.4.4
cycler             0.10.0
czifile            2019.7.2
decorator          4.4.2
deprecat           2.1.1
dill               0.3.4
fastprogress       1.0.2
filelock           3.6.0
Fiona              1.8.20
GDAL               3.3.3
geopandas          0.10.2
imagecodecs        2021.2.26
imageio            2.9.0
importlib-metadata 4.9.0
iniconfig          1.1.1
jmespath           0.10.0
keyboard           0.13.5
kiwisolver         1.3.1
lxml               4.6.2
matplotlib         3.3.4
munch              2.5.0
netCDF4            1.5.8
networkx           2.5
numpy              1.19.3
opencv-python      4.5.1.48
packaging          20.9
pandas             1.2.3
patsy              0.5.2
Pillow             8.1.2
pip                21.3.1
pip-review         1.1.0
pkgconfig          1.5.2
pluggy             1.0.0
psutil             5.8.0
py                 1.11.0
pycparser          2.20
pymc3              3.11.5
pyparsing          2.4.7
pyproj             3.2.1
PySide2            5.15.2
pytest             7.1.1
python-dateutil    2.8.1
pytz               2021.1
pyvips             2.1.14
PyWavelets         1.1.1
pywin32            300
Rtree              0.9.7
s3transfer         0.5.0
scikit-image       0.18.1
scipy              1.7.3
semver             2.13.0
setuptools         41.2.0
Shapely            1.8.0
shiboken2          5.15.2
six                1.15.0
slideio            0.6.2
Theano-PyMC        1.1.2
tifffile           2021.3.17
tomli              2.0.1
tqdm               4.62.3
turboactivate      4.0.3
typing_extensions  4.0.1
urllib3            1.26.7
wheel              0.36.2
winshell           0.6
wrapt              1.14.0
wxPython           4.1.1
xarray             0.20.2
zipp               3.6.0
WARNING: You are using pip version 21.3.1; however, version 22.0.4 is available.
You should consider upgrading via the 'c:\program files\python37\python.exe -m pip install --upgrade pip' command.


D:\Users\Doug\UltivueSWDev\bayesian_estimator>python --version
Python 3.7.7

D:\Users\Doug\UltivueSWDev\bayesian_estimator>
```

-------------------------

Any help would be very much appreciate as this look like a great tool!  
Thank you! 
Doug

**Comment by treszkai** [comment]
Hi @dougwood ,

Could you try the following instead?

```python
best_out = best.analyze_two(group1_data, group2_data, cores=1)
```

**Comment by dougwood** [comment]
Thank you for your help!  But I have found that on Windows adding  if __name__ ==  '__main__':  fixes this issue.
Here's my edited script: 

(Sorry but I can't this to show correctly as python code with indent after the dunder main.)

```
import best
if __name__ ==  '__main__':
   group1_data = [101, 100, 102, 104, 102, 101, 101, 104, 100, 101]
   group2_data = [102, 100,  97, 101, 104, 100, 101, 100, 102, 99, 100, 99]
   best_out = best.analyze_two(group1_data, group2_data)
   fig = best.plot_all(best_out)
   best_out = best.analyze_two(group1_data, group2_data)
   fig = best.plot_all(best_out)
   fig.savefig('best_plots.pdf')
```

**Comment by dougwood** [comment]
See https://stackoverflow.com/questions/18204782/runtimeerror-on-windows-trying-python-multiprocessing

**Comment by treszkai** [comment]
Thanks, good to know.

You can wrap your code or script output in triple backquotes like this and then it's formatted monospace:

![image](https://user-images.githubusercontent.com/30578582/160663413-9d38c04e-24e0-4593-b828-9e1ec886bbc3.png)
